import {
    Any,
    ArrayContainedBy,
    ArrayContains,
    ArrayOverlap,
    Between,
    Equal,
    ILike,
    In,
    IsNull,
    JsonContains,
    LessThan,
    LessThanOrEqual,
    Like,
    MoreThan,
    MoreThanOrEqual,
    Not,
    Or,
    Raw
} from 'typeorm';

export const FilterMapper = {
    any: Any,
    array_contained_by: ArrayContainedBy,
    array_contains: ArrayContains,
    array_overlap: ArrayOverlap,
    between: Between,
    equal: Equal,
    ilike: ILike,
    in: In,
    is_null: IsNull,
    json_contains: JsonContains,
    less_than: LessThan,
    less_than_equal: LessThanOrEqual,
    like: Like,
    more_than: MoreThan,
    more_than_equal: MoreThanOrEqual,
    not: Not,
    or: Or,
    raw: Raw,
}