version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: ./dockerfiles/backend/.dockerfile
    container_name: nestjs11.0.10
    env_file:
      - .env
    environment:
      TZ: Asia/Seoul
      DB_HOST: db
      DB_PORT: 5432
    working_dir: /app
    restart: always
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:3000/health || exit 1" ]
      interval: 5s
      retries: 5
      start_period: 10s

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./dockerfiles/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "${DOCKER_OPEN_PORT:-80}:80"
    restart: always
    depends_on:
      backend:
        condition: service_started
    environment:
      TZ: Asia/Seoul

  db:
    image: postgis/postgis:16-3.4
    container_name: postgresql16-3.4
    env_file:
      - .env
    environment:
      TZ: Asia/Seoul
      POSTGRES_USER: ${DB_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_DATABASE:-postgres}
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 5s
      retries: 5
    ports:
      - "${DB_PORT:-5432}:5432"
    restart: always