export enum PermissionEnum {
    READ_USER = 'READ_USER',
    WRITE_USER = 'WRITE_USER',
    DELETE_USER = 'DELETE_USER',

    READ_POST = 'READ_POST',
    WRITE_POST = 'WRITE_POST',
    DELETE_POST = 'DELETE_POST',

    READ_COMMENT = 'READ_COMMENT',
    WRITE_COMMENT = 'WRITE_COMMENT',
    DELETE_COMMENT = 'DELETE_COMMENT',

    UPLOAD_FILE = 'UPLOAD_FILE',
    DOWNLOAD_FILE = 'DOWNLOAD_FILE',
    DELETE_FILE = 'DELETE_FILE',
}

export default PermissionEnum;