export enum PermissionEnum {
    READ_USER = 'READ_USER',
    WRITE_USER = 'WRITE_USER',
    DELETE_SOFT_USER = 'DELETE_SOFT_USER',
    DELETE_HARD_USER = 'DELETE_HARD_USER',

    READ_GROUP = 'READ_GROUP',
    WRITE_GROUP = 'WRITE_GROUP',
    DELETE_SOFT_GROUP = 'DELETE_SOFT_GROUP',
    DELETE_HARD_GROUP = 'DELETE_HARD_GROUP',

    READ_MAIL = 'READ_MAIL',
    WRITE_MAIL = 'WRITE_MAIL',
    DELETE_SOFT_MAIL = 'DELETE_SOFT_MAIL',
    DELETE_HARD_MAIL = 'DELETE_HARD_MAIL',

    READ_POST = 'READ_POST',
    WRITE_POST = 'WRITE_POST',
    DELETE_SOFT_POST = 'DELETE_SOFT_POST',
    DELETE_HARD_POST = 'DELETE_HARD_POST',

    READ_COMMENT = 'READ_COMMENT',
    WRITE_COMMENT = 'WRITE_COMMENT',
    DELETE_SOFT_COMMENT = 'DELETE_SOFT_COMMENT',
    DELETE_HARD_COMMENT = 'DELETE_HARD_COMMENT',

    UPLOAD_FILE = 'UPLOAD_FILE',
    DOWNLOAD_FILE = 'DOWNLOAD_FILE',
    DELETE_SOFT_FILE = 'DELETE_SOFT_FILE',
    DELETE_HARD_FILE = 'DELETE_HARD_FILE',

    PERMISSION_MODIFY = 'PERMISSION_MODIFY',
}

export default PermissionEnum;